# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches:
      - master
      - 'release/**'
  pull_request:
    branches: 
      - master
      - 'release/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.0.0
    - name: Set up JDK 1.11
      uses: actions/setup-java@v3.12.0
      with:
        distribution: 'temurin'
        java-version: 11
        cache: 'maven'
    - name: Build with Maven (no tests)
      run: mvn -B package --file pom.xml -Dmaven.test.skip
